### ISSUE TITLE
Project status

### ISSUE THREAD

**Issue by mindrunner** [mskucherawy/OpenARC#123]
What is the status of this project. I do not see a lot of activity and a lot of open tickets / PRs.

Is this the way to go, or are there other open implementations of this standard out there?

**Comment by kurta** [comment]
There are several other open implementations, depending on your language
preference (Perl, Go). I suspect that the open tickets here have mostly
been addressed, but just not cleaned out.

--Kurt Andersen

**Comment by mindrunner** [comment]
Thanks for the clarification. It's not really about language. I want to implement ARC into [docker-mailserver](https://github.com/tomav/docker-mailserver/) and I am looking for the best and most stable solution. Can you point me to the other implementations and/or give recommendations?

See [here](https://github.com/tomav/docker-mailserver/issues/1346)

**Comment by kurta** [comment]
How do you currently support DKIM? Using a matching ARC implementation
would probably be the lowest friction (I'll look up the other
implementations any send along links later today).

--Kurt

**Comment by mindrunner** [comment]
Hi Kurt! Thanks for jumping in! :)

[docker-mailserver](https://github.com/tomav/docker-mailserver) is using [OpenDKIM](http://www.opendkim.org/). Does that answer the question?

Not sure how related this is, but [docker-mailserver](https://github.com/tomav/docker-mailserver) does not use [rspamd](https://www.rspamd.com/) (yet). See https://github.com/tomav/docker-mailserver/issues/975

I am mentioning this, because I saw [Mailu](https://mailu.io/) implemented ARC by using [rspamd](https://www.rspamd.com/). Seemed quite simple there. The [patch](https://github.com/Mailu/Mailu/pull/616) is tiny.

**Comment by kurta** [comment]
Yes, rspamd has had ARC support for quite some time. OpenARC is pretty much
the counterpart for OpenDKIM. You can find a list of the other
implementations at http://arc-spec.org/?page_id=79 and I know from earlier
correspondence that there is also a recent Golang implementation published
at https://github.com/Viruthagiri/go-emailauth/blob/master/README.md

--Kurt

**Comment by mindrunner** [comment]
Alright, thanks. So I suppose I have to / should go with OpenARC if we are already using OpenDKIM, right? 

I feel a little bit lost and the documentation seems quite thin. Any poke to the right starting point?

**Comment by kurta** [comment]
That's probably reasonable. Try sending a query to arc-discuss@dmarc.org -
there may be a few people there with starter guidance readily at hand.
Adding that into the repo sounds like it would be a good addition :-)

--Kurt

**Comment by mindrunner** [comment]
Found this: https://github.com/trusteddomainproject/OpenARC/pull/120

@AntiFreeze any chance, we can merge some of the open PRs? :)

**Comment by flowerysong** [comment]
I would currently be wary of using OpenARC unless you're planning to maintain your own custom builds and watch for available patches; if I were relying on upstream releases to address major interoperability issues like #121 we would evidently still be waiting and a huge chunk of our traffic would be handled incorrectly.

**Comment by mindrunner** [comment]
Yes, I fully agree. This is why I created this thread. But what are my options?

**Comment by AntiFreeze** [comment]
@mindrunner this project is still active, thank you for reaching out.

The availability of the primary developers was dramatically reduced last year, which slowed down responses to new issues. We've been working on expanding coverage so that new issues/PRs/bugs/etc. are all dealt with in a timely manner. We're not quite there yet, though.

I'll check with @mskucherawy, but I thought issues like #121 were resolved a while ago, and if all we need is a new release and some packages to help people deploy this widely, we'll get on that ASAP.

**Comment by mindrunner** [comment]
Hi @AntiFreeze 
Thank you for answering! I am happy to hear, this is making progress and I can/will help wherever I can! :)

I started working on the integration into [docker-mailserver](https://github.com/tomav/docker-mailserver) and it looks quite good so far.

Let's get the open PRs merged and tickets cleaned up. That would be great. Also official builds deb/rpm/tar.gz will be really helpful. :)

> We've been working on expanding coverage

What does that mean in specific? Are you hiring people?

**Comment by flowerysong** [comment]
@AntiFreeze It's now been two months since your comment claiming this project is active, and a total of six months since #121 was opened. This is a one-line change that fixes parsing of seals generated by Microsoft (and possibly other implementations), and no maintainer has cared enough to merge it, let alone cut a new release.

The project might not be dead, but it's definitely not active.

**Comment by mindrunner** [comment]
+1

**Comment by kroeckx** [comment]
Which seems to be about the same state as OpenDMARC and OpenDKIM, which are also from The Trusted Domain Project . OpenDMARC had it's last commit and release 3 years ago while it has several unfixed security issues. OpenDKIM had it's last release 5 years ago, with single commit that fixed a typo 3 years ago.

**Comment by martinbogo** [comment]
And we're up and running again.  I'm the maintainer, and Murray and I are working on new releases.  Beta2 is up with a minor documentation fix and I'm doing code merges and regression testing on a number of issues on OpenARC/DMARC/DKIM to bring it in line with the requirements of the downstream integrators.  

Closing this issue.
