### ISSUE TITLE
DMARC failed

### ISSUE THREAD

**Issue by mindrunner** [mskucherawy/OpenARC#126]
I just got an email from zendesk@crypterium. My ARC-enabled server forwarded it to Gmail. Gmail reports that DMARC failed. Is that an issue on the sender's side? Or is there a problem in my configuration:

```
Delivered-To: me@gmail.com
Received: by 2002:a67:ce12:0:0:0:0:0 with SMTP id s18csp144897vsl;
        Tue, 7 Jan 2020 16:48:45 -0800 (PST)
X-Google-Smtp-Source: APXvYqxqLlLcEVjlczm7o4ECRqp+ndsGo0CyuiHST4SLBs9E3XJlDbcIQSlZw7UrvheQWcxjRK0L
X-Received: by 2002:a1c:1b41:: with SMTP id b62mr855403wmb.53.1578444525749;
        Tue, 07 Jan 2020 16:48:45 -0800 (PST)
Return-Path: <SRS0=IhDU=25=crypterium.com=support@domain.com>
Received: from mx0.domain.com (mx0.domain.com. [111.111.111.111])
        by mx.google.com with ESMTPS id k4si611020wmj.82.2020.01.07.16.48.45
        for <me@gmail.com>
        (version=TLS1_2 cipher=ECDHE-RSA-CHACHA20-POLY1305 bits=256/256);
        Tue, 07 Jan 2020 16:48:45 -0800 (PST)
Received-SPF: pass (google.com: domain of srs0=ihdu=25=crypterium.com=support@domain.com designates 111.111.111.111 as permitted sender) client-ip=111.111.111.111;
Authentication-Results: mx.google.com;
       dkim=pass header.i=@zendesk.com header.s=zendesk1 header.b=eHD631x7;
       arc=fail (signature failed);
       spf=pass (google.com: domain of srs0=ihdu=25=crypterium.com=support@domain.com designates 111.111.111.111 as permitted sender) smtp.mailfrom="SRS0=IhDU=25=crypterium.com=support@domain.com";
       dmarc=fail (p=REJECT sp=REJECT dis=QUARANTINE) header.from=crypterium.com
X-Virus-Scanned: Yes
Received-SPF: Pass (mailfrom) identity=mailfrom; client-ip=188.172.138.3; helo=outbyoip3.pod18.euc1.zdsys.com; envelope-from=support@crypterium.com; receiver=<UNKNOWN>
Authentication-Results: mx0.domain.com; dmarc=pass (p=reject dis=none) header.from=crypterium.com
ARC-Filter: OpenARC Filter v0.1.0 mx0.domain.com 786E2617C6
Authentication-Results: mx0.domain.com; arc=none
ARC-Seal: i=1; a=rsa-sha256; d=domain.com; s=openarc; t=1578444523; cv=none; b=HYcMFcAskudn16ZYc9dcyIGRXCxgF7RdBrLzATKdPZNnJVLcxUwZZSq/lMmeSSzHIKkC8K/fBRgVZmUFWKaytdgsGvT2lNKPLaLrGWwWsmih32ipLRxhMGCGwb+Tce8RB9lkVMN5mfbygM/s+kZkw2x2RgmNRgjv2NyE0B0mtuUObhQO2S2nP0mCOsCM1PUnJFj9FLNXkcolZZd/ff36DEQUo8xUdLC3E7BURa7m8bVOwnkllYw1mx+YJlKGIvh0+GcAXjog/o13zJ//A/28/NQJ9UX928zkntzKNOfkmW1RNLmUuhd9zbs5OTrshYoraUYC8+t+nWPJm2GSj+yqiQ==
ARC-Message-Signature: i=1; a=rsa-sha256; d=domain.com; s=openarc; t=1578444523; c=relaxed/simple; bh=s5Qa6XIJ9QikGsu4nqJQcMfH1PWc6Xvr5X19uD0sw3Q=; h=Received-SPF:Received:Date:From:Reply-To:To:Message-ID:
	 In-Reply-To:Subject:Mime-Version:Content-Type:
	 Content-Transfer-Encoding:X-Delivery-Context:Auto-Submitted:
	 X-Auto-Response-Suppress:X-Mailer:X-Zendesk-From-Account-Id:
	 X-Zendesk-Message-Id:DKIM-Signature; b=P9J5psCs5bZtQQJfHT9/MlTGjnHJ/Fd/bKrIDR5bCnRlGCUQnl4FA7owqGiVGpZGfelwDHYDKKgwO5XcV/Jf7kjREdfUoRPQ6CPu+knW7koYzPPlaN4PJe9BImTIkEPHSFrdBgFuiB8s2QsBapgVswsenWlNX97Fmykbf3WIQmdigQBsEpAPsLbtbYVkqhWkOhif9AcwOI8ZO9abjpqj11lkB1kpZgGOvGeo65+9wVPLeR+HBBho2IMtZJYdTtmr3MhQL1qtkmFFKaPSvjtmDGmbBvBXKn4N16RN3rODQFgp5bv8aFZzryLwrI10htn+yDbrOO7LoHc7I+NaTVoeDw==
ARC-Authentication-Results: i=1; mx0.domain.com; dkim=pass (2048-bit key; unprotected) header.d=zendesk.com header.i=@zendesk.com header.b=eHD631x7; dkim-atps=neutral; arc=none
Authentication-Results: mx0.domain.com; dkim=pass (2048-bit key; unprotected) header.d=zendesk.com header.i=@zendesk.com header.b="eHD631x7"; dkim-atps=neutral
Received: from outbyoip3.pod18.euc1.zdsys.com (outbyoip3.pod18.euc1.zdsys.com [188.172.138.3]) by mx0.domain.com (Postfix) with ESMTPS id 786E2617C6 for <crypterium@domain.com>; Wed,
  8 Jan 2020 00:48:43 +0000 (UTC)
Received: from zendesk.com (unknown [10.218.221.64]) by outbyoip3.pod18.euc1.zdsys.com (Postfix) with ESMTP id 1D17D800077 for <crypterium@domain.com>; Wed,
  8 Jan 2020 00:48:42 +0000 (UTC)
Date: Wed, 08 Jan 2020 00:48:42 +0000
From: Crypterium Service <support@crypterium.com>
Reply-To: Crypterium Service <support@crypterium.com>
To: lukas <crypterium@domain.com>
Message-ID: <YD6X3OK3DV_5e1526e9de528_1750b3fd55e0bcf2011235b_sprut@zendesk.com>
In-Reply-To: <YD6X3OK3DV@zendesk.com>
Subject: [Crypterium Service] Request: 91298
Mime-Version: 1.0
Content-Type: multipart/alternative; boundary="--==_mimepart_5e1526ea177ad_1750b3fd55e0bcf20112415"; charset=utf-8
Content-Transfer-Encoding: 7bit
X-Delivery-Context: event-id-502284706200
Auto-Submitted: auto-generated
X-Auto-Response-Suppress: All
X-Zendesk-From-Account-Id: a6f3d33
X-Zendesk-Message-Id: <YD6X3OK3DV_5e1526e9de528_1750b3fd55e0bcf2011235b_sprut@zendesk.com>
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=zendesk.com; q=dns/txt; s=zendesk1; t=1578444522; bh=1UayuudIiyeNZNshHKqW0PdPBExQtCPqpe2oipMSFg0=; h=date:from:reply-to:to:message-id:in-reply-to:subject:mime-version:content-type:content-transfer-encoding; b=eHD631x7fah5QKjVtgoCANakzlTNW045aIqJmtYw/ynnDUiQxPFJez+T8+Z7sbRXy9UkMC37h6XSQ9vW/fT8bmGFBsH89iIGFDUCUo9gQAtAPHmFsJGZ6GbRxftjqfNjgHhjPXz3AY/6cgY5jRHtsUC883VW7/QoOgix3Nx32aMNvXBYoR8kzPK5bbfvorkRWB8LjQvpDqLRwNE2QM3G7GEzjv51rXUXRLmTMtwolSKKNxlBA6YGbyil3i7k3ucwmfI59k2wxWL/veogP23q8o0xlw1u6UFJuuUGHXZzVrYnXmxJiejV3z7lZSbJLlLg4aNBF4OE1lXdamCgsjsMGw==
```

**Comment by mindrunner** [comment]
I am confused. I Disabled ARC and it is still failing. However, DMARC entries on `crypterium.com` as well as on `zendesk.com` looking fine. I checked with: https://mxtoolbox.com/dmarc.aspx

Furthermore, both domains set their policy to reject. However, Gmail puts it into quarantaine (spam folder). 

Are there any explanations to this? Sorry, I am a bit off-topic now. I first assumed, it might be a problem with OpenARC, but I think it is not.

**Comment by flowerysong** [comment]
ARC does not change the result of DMARC evaluation. The message as received by Google does not pass SPF for crypterium.com (since the RFC5321.MailFrom is `@domain.com` due to SRS) and it does not pass DKIM for crypterium.com (it has a valid DKIM signature, but for zendesk.com), so it fails DMARC.

The message ends up quarantined because Google chose (due to local policy) to do so: `dmarc=fail (p=REJECT sp=REJECT dis=QUARANTINE)`

**Comment by mindrunner** [comment]
@flowerysong thank you for the answer. This brings at least a bit clarity for me.

> The message as received by Google does not pass SPF for crypterium.com (since the RFC5321.MailFrom is @domain.com due to SRS)

But Gmail always sais SPF pass (with my server IP). Because that's where the mail comes from. I am aware of this problem. Not sure if it actually is a problem. But this is why there is also DKIM, DMARC and ARC, right?

> it does not pass DKIM for crypterium.com (it has a valid DKIM signature, but for zendesk.com), so it fails DMARC.

Yeah, this is what I was wondering about. Is that a configuration issue on their side? I cannot imagine that all zendesk emails sent in the customer;s name fail, or do they? Same problem should then also occur with newsletters a la Mailchimp? (I just checked a Mailchimp email and there is no DMARC signature...)

> The message ends up quarantined because Google chose (due to local policy) to do so: dmarc=fail (p=REJECT sp=REJECT dis=QUARANTINE)

Is there any reasonable explanation why google sometimes decides for quarantaine and sometimes rejects. (I have had some emails from dhl.com domain rejected, they also have the p=REJECT flag set)

**Comment by kurta** [comment]
I don't see that your server (mx0.domain.com) did any sort of DMARC
evaluation. At least it does not report having done so. Crypterium mail has
an include in their SPF record to permit sending from zendesk. I'm not sure
whether your assertion of a dmarc=pass in the AAR would make a difference
for Google's eventual disposition, but their ML system will require some
amount of "trustable" traffic before it starts relying on your ARC headers.

--Kurt

**Comment by flowerysong** [comment]
> > it does not pass DKIM for crypterium.com (it has a valid DKIM signature, but for zendesk.com), so it fails DMARC.
> 
> Yeah, this is what I was wondering about. Is that a configuration issue on their side? I cannot imagine that all zendesk emails sent in the customer;s name fail, or do they?

It's fine for direct mail delivery (and that's probably all they care about), because their RFC5321.MailFrom is @crypterium.com and Zendesk is in their SPF record. [DMARC breaks indirect mail flows](https://tools.ietf.org/html/rfc7960).

> Is there any reasonable explanation why google sometimes decides for quarantaine and sometimes rejects. (I have had some emails from dhl.com domain rejected, they also have the p=REJECT flag set)

Local policy is allowed to override DMARC results. That's perfectly reasonable.

**Comment by kurta** [comment]
I'd be sad to find out that Zendesk does not support DKIM signing for their
customers, but it probably would require a delegated subdomain or other
mechanisms which crypterium has apparently not invested time to set up.

--Kurt

**Comment by mindrunner** [comment]
It's not the only thing crypterium messed up ;)

Thanks for all the input! Closing this now.

Lukas
