### ISSUE TITLE
OpenARC setup with other milters

### ISSUE THREAD

**Issue by glts** [mskucherawy/OpenARC#139]
Could someone please explain the recommended setup of OpenARC with Postfix? What is the required or recommended sequence of milters doing SPF, DKIM, DMARC, and ARC?

Currently I’m using the following milters in Postfix:

```
smtpd_milters =
  unix:spf/spf-milter.sock
  unix:opendkim/opendkim.sock
  unix:opendmarc/opendmarc.sock
  unix:spamassassin/spamassassin-milter.sock
```

Where does OpenARC fit in? It has to be *after* OpenDKIM and *before* OpenDMARC, is that right? (And can it be made to work at all in the current state?)

**Comment by glts** [comment]
The answer seems to be yes, the OpenARC milter should be just before OpenDMARC, because OpenDMARC will consume `Authentication-Results` added by OpenARC to override a failing DMARC check. See here:

https://github.com/trusteddomainproject/OpenDMARC/blob/rel-opendmarc-1-4-0-Beta1/opendmarc/README#L192-L208

To make it work with OpenDMARC, first set the final receiver parameter in the OpenARC configuration:

    FinalReceiver yes

Then add the following setting to the OpenDMARC configuration, where `community_sealer_whitelist` is the whitelist provided in project [trusteddomainproject/ARC_Community_Sealers](https://github.com/trusteddomainproject/ARC_Community_Sealers).

    DomainWhitelistFile /path/to/community_sealer_whitelist

Then it should work, at least for verification.

**Comment by abeverley** [comment]
Just to add to this, I think the ordering depends on what you are doing. If you are forwarding and sealing messages, then I think OpenDMARC should be _before_ OpenARC, so that OpenARC can include the results from OpenDMARC in its signature.
