### ISSUE TITLE
Memory leak in arc_init/arc_close

### ISSUE THREAD

**Issue by InterLinked1** [mskucherawy/OpenARC#165]
It appears that `arc_close` does not free all of the memory allocated in `arc_init`, namely this memory is leaked and never freed:

```
lib->arcl_flist = (u_int *) malloc(sizeof(u_int) * lib->arcl_flsize);
```

If the library is initialized and closed multiple times, these leaks will start accumulating, so this is not a constant memory leak.

This patch fixes the memory leak:

```
diff --git a/libopenarc/arc.c b/libopenarc/arc.c
index 4188269..e67869b 100644
--- a/libopenarc/arc.c
+++ b/libopenarc/arc.c
@@ -831,6 +831,7 @@ arc_init(void)
 void
 arc_close(ARC_LIB *lib)
 {
+       free(lib->arcl_flist);
        free(lib);
 }
```

**Comment by flowerysong** [comment]
You appear to be looking at an outdated version of the code. 

https://github.com/trusteddomainproject/OpenARC/blob/eb430dbdeee9f502295fe7a7d5041dfca3f00745/libopenarc/arc.c#L841

**Comment by InterLinked1** [comment]
> You appear to be looking at an outdated version of the code.
> 
> https://github.com/trusteddomainproject/OpenARC/blob/eb430dbdeee9f502295fe7a7d5041dfca3f00745/libopenarc/arc.c#L841

I was looking at the master branch. I see now that the `develop` branch is what should be used, not master. I'll change my upstream, but maybe the documentation should indicate this?

**Comment by flowerysong** [comment]
The project is dead, so you shouldn't hold your breath.

**Comment by InterLinked1** [comment]
> The project is dead, so you shouldn't hold your breath.

Yeah, I'd noticed... which is a shame, since this is really the only C library for ARC. Noticed that's what simpta uses as well (hard to find examples for this, and there's no usage documentation like there is for TDP's other libraries).

I guess I'll close this issue for now.
