### ISSUE TITLE
Just does not work?

### ISSUE THREAD

**Issue by rotdrop** [mskucherawy/OpenARC#20]
No flames intended, this is work in progress. Nevertheless I thought I'd give it a try :) So just some feed-back, partly redundant with other issueds reported here

-  it doesn't build, unless you apply the fixes from the recent build-pull-request. It just does not build otherwise

-  the config-file man-page is just out of date

-  just one working setup example for installation? Daemon complains: domain missing, key-file missing, selector missing. If I supply (just as a quick hack) the config from opendkim, then the daemon is caught in an infinite loop and at some point catches the kernels out-of-memory-oom.

One working example build and config? Or should we just wait a little bit longer until the project has stabilized?

All of the above just sounds too negative. My kind thanks to the author for his efforts! If you have something I could test: I have two servers under my control, including a test-mailing list in order to ping-pong messages through the respective validation frame-works.

**Comment by mskucherawy** [comment]
Given that this is a work in progress, pull requests that fix any or all of this are welcome.

But yes, the intent is to clean up all of this.  It's modeled on OpenDKIM, which has all of the things you're talking about here.
