### ISSUE TITLE
ARC-Seal: "a=" tag misformatted

### ISSUE THREAD

**Issue by smjones** [mskucherawy/OpenARC#5]
I have the openarc 0.1.0 milter running with sendmail, in a very simplistic configuration. Sending to an address on the box, openarc is signing/sealing the message just before local delivery to a file. In the ARC-Seal: header, the "a=" tag appears to be misformatted - perhaps a pointer issue, since I haven't found this particular typo in the source yet. Here's the relevant part of the header that was applied:

`ARC-Seal: i=1; a=rsa-:ha1; ...
ARC-Message-Signature: i=1; a=rsa-sha1; ...`

Attaching the whole message for reference.

[msgh107oHyY.txt](https://github.com/mskucherawy/OpenARC/files/321026/msgh107oHyY.txt)

**Comment by mskucherawy** [comment]
This seems to have been fixed, probably by 11124e25b0ef7dcb8d8a71eaadec6b795e1e85e0.
