### ISSUE TITLE
Crashing in arc_process_set()

### ISSUE THREAD

**Issue by smjones** [mskucherawy/OpenARC#6]
I've got openarc 0.1.0 in a simplistic configuration, with sendmail and mailman

I'm running the milter, configured with --enable-debug, in the foreground so I can get more information when it dies. Here's what I'm seeing from the command line when the bug is triggered:

629 indirect# sbin/openarc -f -l -c etc/mail/openarc.conf
Assertion failed: (0), function arc_process_set, file arc.c, line 1302.
Abort
630 indirect# 

Only one of the three /tmp/arc.\* files is not zero-length when this happens. Attaching the one that is populated.
[arc.Ypd8lB.txt](https://github.com/mskucherawy/OpenARC/files/321164/arc.Ypd8lB.txt)

I changed the alias for the list to capture a copy of the inbound message, too. I notice 
[message-interop.txt](https://github.com/mskucherawy/OpenARC/files/321166/message-interop.txt)

Milter configuration, too:
[openarc.conf.txt](https://github.com/mskucherawy/OpenARC/files/321173/openarc.conf.txt)

**Comment by mskucherawy** [comment]
Resolved last year.
