### ISSUE TITLE
message rejected, "error processing at end of header"

### ISSUE THREAD

**Issue by smjones** [mskucherawy/OpenARC#7]
An error in the OpenARC milter appears to be causing the MTA to refuse to accept messages that contain ARC headers. Issue was reported by a tester sending a message signed by another implementation; I've reproduced it with the steps below.

Take the following message and send it through the auto-reply function over at indirect.dmarctest.org (I've obfuscated addresses lamely below):

```
To: autoreply@XXXXXX.org
From: smj@XXXXXX.com
Subject: Trying something w/ ARC headers

This is a completely bogus message.
--S.
```

That message goes through, and the reply comes with fresh ARC headers as expected.

However If I take the same message and insert a set of ARC headers generated by the current OpenARC milter for a different message:

```
ARC-Seal: i=1; a=rsa-sha1; d=dmarctest.org; s=indirect; t=1474650710; b=hni1X3UW
0/PFPAos+lKXM1PyalZotcewWJq2lhlo4hCr5vwgZTcH/Wl7VoTeTamC1AIDNmBGoVjEUOoA0aY8mr60
lMmU7Pa+4Gh9k5+hVudFl7X6x85VTZHhcUB5iU38FbCn0NLCrr4D4BxR0ZrgkUMiV4w4SoiHhpj+av/1
PCQ=
ARC-Message-Signature: i=1; a=rsa-sha1; d=dmarctest.org; s=indirect; t=147465071
0; bh=47DEQpj8HBSa+/TImW+5JCeuQeRkm5NMpJWZG3hSuFU=; h=Received:Date:Message-Id:M
IME-Version:From:To:Subject:X-Mailer:Organization:Content-Type; b=myMPIWfiJDsOb2
g5iG8cOMfjHFuJp5mLPvzPHRr/RzxKuzEP6O6K2Gea1KVvRubxsvbG2G/z+V+uWmDzmUpebjLG+fK09k
OY5CNbTBZK5oMYU+prVLHStapPlatedDA5WIc48NMg6v90qB2Wi2hcnMgBwA7LLpeqk3HeswvoRiE=
ARC-Authentication-Results: i=1 indirect.dmarctest.org; none
To: autoreply@XXXXXX.org
From: smj@XXXXXX.com
Subject: Trying something w/ ARC headers

This is a completely bogus message.
--S.
```

I do not get an ARC failure -- in fact, the milter appears to cause the MTA to refuse to accept the message. Here is what the MTA logs:

```
Sep 23 10:24:18 indirect sm-mta[85102]: STARTTLS=server, relay=segv.crash.com [IPv6:2001:470:1:1e9::4415], version=TLSv1, verify=FAIL, cipher=DHE-RSA-AES256-SHA, bits=256/256
Sep 23 10:24:18 indirect sm-mta[85102]: u8NHOGtr085102: from=<smj@XXXXXX.com>, size=1912, class=0, nrcpts=1, msgid=<201609231724.u8NHO3G3043910@segv.crash.com>, proto=ESMTPS, daemon=IPv6, relay=segv.crash.com [IPv6:2001:470:1:1e9::4415]
**Sep 23 10:24:18 indirect openarc[84412]: u8NHOGtr085102: error processing at end of header**
Sep 23 10:24:18 indirect sm-mta[85102]: u8NHOGtr085102: Milter: data, reject=451 4.3.2 Please try again later
Sep 23 10:24:18 indirect sm-mta[85102]: u8NHOGtr085102: to=<autoreply@XXXXXX.org>, delay=00:00:00, pri=31912, stat=Please try again later
```

Source of OpenARC milter is a tarball prepared by msk last night (should be Latest commit 0652d86).
MTA is sendmail 8.15.2
Host OS is FreeBSD 10.2-RELEASE-p14

**Comment by smjones** [comment]
Erf, the "**" in the log message was supposed to make the line bold, but apparently that's not legal within a code/preformat block. Does not appear in original.

**Comment by mskucherawy** [comment]
This doesn't seem to be happening in the latest builds.
